### ISSUE TITLE
Light background needed.

### ISSUE THREAD

**Issue by nolboo** [yous/vim-open-color#1]
I use this color scheme with vim-markdown. Could you please make light background mode for day light?

**Comment by yous** [comment]
Thanks for the suggestion. I'll work on this! But it may take some time to adjust colors.

**Comment by yous** [comment]
Hi, I just added the version for light background. Hope you like it.

**Comment by nolboo** [comment]
I like light background of open color. Thank you for your rapid and great response! 😺
