### ISSUE TITLE
Request: Terminal colors support

### ISSUE THREAD

**Issue by ghost** [yous/vim-open-color#2]
VIM has `:terminal` support. Can you please introduce color support fro vim terminal?

**Comment by yous** [comment]
Thanks for the suggestion. I'll add them soon.

Until that time, take a look at my [vimrc](https://github.com/yous/dotfiles/blob/20041075492a08a89027dfa17c324400e83fdc81/vimrc#L470-L494) which sets Tomorrow Night colors for terminal.

**Comment by yous** [comment]
Sorry for the delay, I've just updated open-color.vim to support terminal colors in https://github.com/yous/vim-open-color/commit/47289c43e94a434f76d2bc9c800f1de3097a02e5.
